name: 'Sync Docs'
description: 'Sync Docs'
inputs:
  username:
    description: 'Knowl username'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checking out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo $username
      shell: bash
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: sync-linked-pages.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
        GITHUB_REF: ${{github.ref}}
        CURRENT_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
        RANDOM_ENV: bbc
