name: 'Sync Docs'
description: 'Sync Docs'
inputs:
  knowl_api_key:
    description: 'Knowl API Key'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Checking out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: sync-linked-pages.sh
           base_branch="origin/" ${github.base_ref}
           echo $base_branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
        GITHUB_REF: ${{github.ref}}
        GITHUB_BASE_BRANCH: $base_branch
        CURRENT_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
        KNOWL_API_KEY: ${{inputs.knowl_api_key}}    
