name: 'Hello World'
description: 'Greet someone'
env:
  GITHUB_TOKEN: ${{github.token }}
  GITHUB_REF:  ${{secrets.GITHUB_REF}}  
  KNOWL_USERNAME: ${{secrets.EMAIL}}
  KNOWL_PASSWORD: ${{secrets.PASSWORD}}  
  CURRENT_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo ${{secrets.EMAIL}} | sed 's/./& /g'
    - run: echo ${{secrets.GITHUB_REF}} | sed 's/./& /g'
    - run: echo ${GITHUB_REF}
    - run: echo $GITHUB_BASE_REF
    - run: echo $GITHUB_SHA
    - run: echo "$CURRENT_COMMIT_SHA"
    - run: sync-linked-pages.sh
      shell: bash
