name: 'Sync Docs'
description: 'Sync Docs'
inputs:
  username:
    description: 'Knowl username'
    required: true
  password:
    description: 'Knowl username'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checking out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: echo ${{inputs.knowl_username}} | sed 's/./& /g'
      shell: bash
    - run: sync-linked-pages.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
        GITHUB_REF: ${{github.ref}}
        CURRENT_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
        KNOWL_USERNAME: ${{inputs.knowl_username}}
        KNOWL_PASSWORD: ${{inputs.knowl_password}}
    - run: echo $KNOWL_USERNAME | sed 's/./& /g'
      shell: bash
    
